CREATE DATABASE ConnectPlus;
GO

USE ConnectPlus;
GO

CREATE TABLE TipoContato(
IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),

Titulo NVARCHAR(255) NOT NULL

);
GO

CREATE TABLE Contatos(
IdContatos UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),

Nome NVARCHAR(255) NOT NULL,
Imagem NVARCHAR(255),
FormaContato NVARCHAR(255) NOT NULL,

IdTipoContato UNIQUEIDENTIFIER 
FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);
GO